project: 
  type: website
  
website: 
  page-navigation: true
  title: "Students Mastering Intriguing Testable Hypotheses" 
  site-url: "https://justinsmithecon.github.io/econcomp" 
  comments: 
    hypothesis:
      theme: clean
      openSidebar: false    
  open-graph: true
  twitter-card: 
    creator: "@justinsmithecon"    
  sidebar:
    logo: "images/hex.png"
    title: "Students Mastering Intriguing Testable Hypotheses"
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Overview
      - href: report.qmd
        text: Leaderboard
      # - href: help.qmd
      #   text: Help        


format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true