---
title: "Students Mastering Intriguing Testable Hypotheses"
subtitle: "Laurier Economics Student Competition 2025-26"
---

## Overview

### Description

Welcome to the third annual Students Mastering Intriguing Testable Hypoheses (SMITH) competition.  We run this event annually to create a fun learning experience for Laurier Economics students outside of the classroom.

The objective of this year's competition is to predict end of season winning percentage by team in the NHL using information available at the beginning of a season. Professional sports provide a natural laboratory for economic analysis. NHL teams operate under budget constraints, face uncertainty, and must make forward-looking decisions using imperfect information. Using only information available before the season begins, participants are asked to forecast team performance out of sample. The goal is not to explain past outcomes, but to make accurate predictions under uncertainty, applying core economic ideas. The methods used here mirror those economists use to forecast employment, productivity, and growth in real-world settings.

### How to Participate

-   Sign up your team <!--[{{< fa arrow-up-right-from-square >}}](https://wlu.ca1.qualtrics.com/jfe/form/SV_3mbqwMfTOQCP5Ge)-->
-   Download the data [{{< fa arrow-up-right-from-square >}}](#sec-data)
-   Create your model and generate predictions
-   Submit your predictions [{{< fa arrow-up-right-from-square >}}](#sec-submit)

### Evaluation

Each submission is scored on its **Root Mean Square Error (RMSE)**, a measure of the average error of the prediction. The submission with the lowest RMSE wins.

### Timeline

The competition will run through the Winter 2026 semester.  See below for key dates:

-   **Sign Up Window** - February 6, 2026 to February 20, 2026 (CLOSED)
-   **Competition Opens** - February 23, 2026
-   **Competition Closes** - 11:59pm, March 27, 2026.

### Prizes

Prizes are allocated separately by year level of the team members. If a team has a mix of year levels, the prize is allocated to the highest year level of the team members. Year levels are: 1st, 2nd, 3rd, 4th, and Masters.

-   **1st Place at Each Year Level**: \$300 split between team members.

Your achievement will also be celebrated at a year-end event where we will celebrate the accomplishments of economics students over the past academic year.

## Data {#sec-data}

The underlying data for the competition is a collection of NHL team stats downloaded from Natural Stattrick.  

You are provided with two datasets: 1) the "training" data, and 2) the "evaluation" data. You will create and estimate your model with the training dataset, which for the 2014-15 through the 2023-24 seasons has current year winning percentage, a large set of statistics for the previous season, and the average of those same statistics for the prior three seasons.  Once you have a submission ready you will generate your predictions for winning percentage for the 24-25 season with the evaluation dataset, which has all the same variables as the training dataset minus the current season winning percentage. 

When you submit your predictions based on the evaluation data, we will compute the RMSE using the true 24-25 winning percentage for those records and report it on the leaderboard at the end of each day.

Download the data in your preferred format below.

|           |                                   |                                   |
|----------------|----------------------------|----------------------------|
| File Type | Training Data                         | Evaluation Data                   |
| csv       | [train.csv](data/train.csv) | [eval.csv](data/eval.csv) |
| dta       | [train.dta](data/train.dta) | [eval.dta](data/eval.dta) |

A data dictionary that describes each variable is here: [Data Dictionary](data/NHL_Data_Dictionary.xlsx)

## Submissions {#sec-submit}

All submissions must be in **.csv** format, and contain only two columns: 1) **team**, the team name; 2) **pwinperc**, the prediction of the 24-25 winning percentage for the team.

The .csv files must be named with your group name in all lower case letters and no spaces. For instance, if your team name is "The Deadweight Losses" then your submissions must all be named **thedeadweightlosses.csv**

Submit your .csv files here: [link to submission form](https://docs.google.com/forms/d/e/1FAIpQLSd3FelT-hZPsH9j8GTaSxlyAuwdYhQWKbO43a2YqqojxyF97Q/viewform?usp=dialog)



## Questions

If you have any questions about the competition or require help with your predictions, contact <a href="mailto:jusmith@wlu.ca">jusmith@wlu.ca</a>

## Rules

**Students can only belong to one team**

A student can only be on a single team

**No sharing code privately between teams**

Each team must work independently to complete the predictions.

**Team limits**

Teams of up to 3 students are allowed.

**Data**

Teams can only use the data provided to create your models. No external data is permitted.

**Eligibility**

Eligible participants are Laurier undergraduate students whose **major** is Economics, Economics and Accounting, Economics and Financial Management, and Economics and Data Analytics during the signup period. If a student subsequently switches programs but remains enrolled at the university, they can remain in the competition.

**Submitting Code**

Students must provide the code that generated their predictions for their final submission only. The code must run and generate the submitted output, otherwise the team is disqualified.
